//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEmpresasEMM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public System.Guid idEmpleado { get; set; }
        public Nullable<System.Guid> idEmpresa { get; set; }
        public Nullable<System.Guid> idDepartamento { get; set; }
        public string Nombre { get; set; }
        public string ApellidoMat { get; set; }
        public string ApellidoPat { get; set; }
        public int TypeRol { get; set; }
        public string direccion { get; set; }
        public int CodigoPostal { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public string Rol { get; set; }
        public string Telefono1 { get; set; }
        public Nullable<int> Telefono2 { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
